snowflake:
  schemaPath: amplify/backend/api/snowflake/schema.json
  includes:
    - graphql/**/*.graphql
  excludes:
    - ./amplify/**
  extensions:
    amplify:
      graphQLApiId: tdzegajokjf47gj7vg6wegeo2q
      codeGenTarget: typescript
      generatedFileName: API.ts
